version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["is_it_ok.sh", "**.in", "**.out", "**.src", "**.IPPcode23"]

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "php"
